#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Params
TARGET_PATH="${1:-}"

function print_usage {
    echo
    echo "Usage: tfenv get [TARGET_PATH]"
    echo
    echo "Example:"
    echo
    echo "  tfenv get prod/rds"
}

function get {
    echo "Run terraform get ${TARGET_PATH}..."
    terraform get "${TARGET_PATH}"
}



if [[ -z "${TARGET_PATH}" ]]
then
    print_usage
    exit 1
fi

get
