#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Params
TARGET_PATH="${1:-}"
RESOURCE_ADDR="${2:-}"
ID="${3:-}"

function print_usage {
    echo
    echo "Usage: tfenv import [TARGET_PATH] [RESOURCE_ADDR] [ID]"
    echo
    echo "Example:"
    echo
    echo "  tfenv import prod/rds aws_iam_account_alias.alias select-prod"
}

function import {
    echo "Run terraform import ${RESOURCE_ADDR} ${ID} for ${TARGET_PATH}..."
    exec terraform import --config=${TARGET_PATH} "${RESOURCE_ADDR}" "${ID}"
}



if [[ -z "${TARGET_PATH}" ]] \
|| [[ -z "${RESOURCE_ADDR}" ]] \
|| [[ -z "${ID}" ]]
then
    print_usage
    exit 1
fi

import
