#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Params
TARGET_PATH="${1:-}"
RESOURCE="${2:-}"

function print_usage {
    echo
    echo "Usage: tfenv destroy [TARGET_PATH] [RESOURCE]"
    echo
    echo "Example:"
    echo
    echo "  tfenv destroy prod/rds module.something"
}

function destroy {
    if [[ -z "${RESOURCE}" ]]
    then
        echo "Run terraform destroy ${TARGET_PATH} all..."
        terraform destroy ${TARGET_PATH}
    else
        echo "Run terraform destroy terraform/${TARGET_PATH} ${RESOURCE}..."
        terraform destroy --target=${RESOURCE} ${TARGET_PATH}
    fi
}



if [[ -z "${TARGET_PATH}" ]] \
|| [[ -z "${RESOURCE}" ]]
then
    print_usage
    exit 1
fi

destroy
