#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Variables
BACKEND_S3_REGION="${BACKEND_S3_REGION:-}"
BACKEND_S3_BUCKET="${BACKEND_S3_BUCKET:-}"
BACKEND_S3_DYNAMODB_TABLE="${BACKEND_S3_BUCKET}-lock"
TF_PLUGIN_DIR="${TF_PLUGIN_DIR:-}"

# Params
TARGET_PATH="${1:-}"

function print_usage {
    echo
    echo "Usage: tfenv init [TARGET_PATH]"
    echo
    echo "Example:"
    echo
    echo "  tfenv init prod/network"
}

function init {
    echo "Run terraform init ${TARGET_PATH}..."

    terraform init \
        -plugin-dir="${TF_PLUGIN_DIR}" \
        -backend=true \
        -backend-config="region=${BACKEND_S3_REGION}" \
        -backend-config="bucket=${BACKEND_S3_BUCKET}" \
        -backend-config="dynamodb_table=${BACKEND_S3_DYNAMODB_TABLE}" \
        -backend-config="key=${TARGET_PATH}" \
        "${TARGET_PATH}"
}



if [[ -z "${TARGET_PATH}" ]]
then
    print_usage
    exit 1
fi

if [[ -z "${BACKEND_S3_REGION}" ]] \
|| [[ -z "${BACKEND_S3_BUCKET}" ]] \
|| [[ -z "${TF_PLUGIN_DIR}" ]]
then
    "Environment variables 'BACKEND_S3_REGION', 'BACKEND_S3_BUCKET', 'TF_PLUGIN_DIR' are required"
    exit 1
fi

init
